/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/admin/AdminController.p.vm.java
 */
package org.apache.cassandra.party.web;

import java.util.List;

import org.apache.cassandra.party.service.NodeInfo;
import org.apache.cassandra.party.service.RingService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;


@Controller
public class RingController {
    
    @Autowired
    private RingService ringService;
    
    
    @RequestMapping("/ring")
    public String ring(Model model) {
        
        List<NodeInfo> infos = ringService.loadNodeInfos("ks"); // TODO
        
        for (NodeInfo ni : infos) {
            System.out.println(ni);
        }
        
        model.addAttribute("nodeInfos", infos);
        
        return "ring"; // todo
    }    
}

